services:
  streamlit:
    build: .
    ports: ["8501:8501"]
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on: [redis]
  
  redis:
    image: redis:alpine
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    
volumes:
  redis_data: